### ISSUE TITLE
Joining online-mode servers is no longer possible

### ISSUE THREAD

**Issue by BigPanda97** [Defective4/Another-Minecraft-Chat-Client#16]
**Describe the bug**
Joining online servers (Mojang Login) is not possible.
(Connection Lost: 
java.io.EOFException)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest, but seems to affect about the last 3 versions of AMC.

**Additional context**
`java.io.IOException: Server returned HTTP response code: 403 for URL: https://sessionserver.mojang.com/session/minecraft/join
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at net.defekt.mc.chatclient.protocol.MojangAPI.makeJSONRequest(MojangAPI.java:162)
        at net.defekt.mc.chatclient.protocol.ClientPacketListener.packetReceived(ClientPacketListener.java:247)
        at net.defekt.mc.chatclient.protocol.MinecraftClient$1.run(MinecraftClient.java:378)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273)
        at net.defekt.mc.chatclient.protocol.io.VarInputStream.readVarInt(VarInputStream.java:77)
        at net.defekt.mc.chatclient.protocol.MinecraftClient$1.run(MinecraftClient.java:327)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.InterruptedException: sleep interrupted
        at java.base/java.lang.Thread.sleep(Native Method)
        at net.defekt.mc.chatclient.ui.Main$89$3.run(Main.java:4109)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.InterruptedException: sleep interrupted
        at java.base/java.lang.Thread.sleep(Native Method)
        at net.defekt.mc.chatclient.protocol.MinecraftClient$2.run(MinecraftClient.java:406)
        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Defective4** [comment]
Are you sure you enter valid credentials?
Also keep in mind that **Microsoft** auth is **not** supported at the moment, you can only login with Mojang account.

**Comment by BigPanda97** [comment]
> Are you sure you are using valid credentials?
Yes, it worked a few days before on AMC with no problems on the older version. But I can re-check it tomorrow using the normal Minecraft client to be sure the login works fine.

> Also keep in mind that **Microsoft** auth is **not** supported at the moment, you can only login with Mojang account.
Yes, it's a Mojang account.

**Comment by BigPanda97** [comment]
Okay, so it looks like Mojang is now blocking ALL accounts which are not migrated to a Microsoft account. So, Microsoft login must be implemented in order to use the AMC again...
